debug: 0
verbose: 1
specif: 0
loading: 1
dummy: 0
log: 1
locale: en_US.ISO-8859-15
log_dir: /var/jester/logs
build_dir: /var/jester/build
lv_size: 4G
lv_swap_size: 512M
mirror: ftp://ftp.fr.debian.org/debian
gateway: 10.0.0.1
netmask: 255.255.255.0
pub_key: /etc/xen-tools/master.pub